### ISSUE TITLE
`izip_longest` not found

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/quail#111]
importing quail in python 3 results in the following error:
```
/opt/conda/lib/python3.6/site-packages/quail/__init__.py in <module>()
----> 1 from .load import load, load_example_data
      2 from .egg import Egg
      3 from .analysis import analyze
      4 from .plot import plot
      5 from .helpers import stack_eggs, crack_egg, recmat2egg, load_egg

/opt/conda/lib/python3.6/site-packages/quail/load.py in <module>()
      5 import re
      6 import csv
----> 7 from itertools import izip_longest
      8 from collections import Counter
      9 import pandas as pd

ImportError: cannot import name 'izip_longest'
```

It looks like `izip_longest` was renamed to `zip_longest` in the Python 3 version of itertools (see [this post](https://stackoverflow.com/questions/5850536/how-to-chunk-a-list-in-python-3))

I think something the following change to `load.py` would fix the issue:
```
import sys
if sys.version_info[0] < 3:
    from itertools import izip_longest
else:
    from itertools import zip_longest as izip_longest
```

**Comment by jeremymanning** [comment]
nvm...seems to be an issue with the version of quail installed in the Sherlock container...

**Comment by jeremymanning** [comment]
hey team-- i'm getting this issue again.  did we resolve it?  if so, how?

**Comment by jeremymanning** [comment]
```
>>> import quail
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/quail/__init__.py", line 1, in <module>
    from .load import load, load_example_data
  File "/usr/local/lib/python3.6/site-packages/quail/load.py", line 7, in <module>
    from itertools import izip_longest
ImportError: cannot import name 'izip_longest'
```

**Comment by paxtonfitzpatrick** [comment]
hey @jeremymanning, are we ready to close this issue?

**Comment by jeremymanning** [comment]
i think so...closing.
